// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LutonesSystem.Models { };

public partial class tb_clientes
{
    [Key]
    public int cl_id { get; set; }

    [Required]
    [StringLength(50)]
    
    public string cl_nome { get; set; }

    [StringLength(15)]
   
    public string cl_cpf { get; set; }

    [StringLength(50)]
   
    public string cl_email { get; set; }

    [StringLength(14)]
   
    public string cl_telefone { get; set; }

    public DateTime? cl_data_cadastro { get; set; }
}