// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LutonesSystem.Models { };
public partial class tb_fornecedores
{
    [Key]
    public int for_id { get; set; }

    [Required]
    [StringLength(50)]
   
    public string for_nome { get; set; }

    [StringLength(20)]
   
    public string for_cnpj { get; set; }

    [StringLength(16)]
   
    public string for_telefone { get; set; }

    [StringLength(50)]
   
    public string for_email { get; set; }

    public DateTime? for_data_cadastro { get; set; }

    [InverseProperty("in_fk_id_fornecedoresNavigation")]
    public virtual ICollection<tb_insumos> tb_insumos { get; set; } = new List<tb_insumos>();
}