// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LutonesSystem.Models { };
public partial class tb_funcionarios
{
    [Key]
    public int fun_id { get; set; }

    [Required]
    [StringLength(50)]
 
    public string fun_nome { get; set; }

    [StringLength(50)]

    public string fun_cargo { get; set; }

    public DateTime? fun_data_cadastro { get; set; }
}