// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LutonesSystem.Models { };
public partial class tb_insumos
{
    [Key]
    public int in_id { get; set; }

    [Required]
    [StringLength(100)]
    public string in_nome { get; set; }

    public int in_quantidade_estoque { get; set; }

    [StringLength(50)]
    public string in_unidade_medida { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal in_preco_unitario { get; set; }

    public int in_fk_id_fornecedores { get; set; }

    [ForeignKey("in_fk_id_fornecedores")]
    [InverseProperty("tb_insumos")]
    public virtual tb_fornecedores in_fk_id_fornecedoresNavigation { get; set; }
}