// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LutonesSystem.Models { };
public partial class tb_produtos
{
    [Key]
    public int prd_id { get; set; }

    [Required]
    [StringLength(100)]
    public string prd_nome { get; set; }

    [StringLength(255)]
    public string prd_descricao { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal prd_preco_venda { get; set; }

    public int prd_qtd_estoque { get; set; }
}