//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LutonesSystem.XPO.LutonesSystem
{

    [Persistent(@"tb_clientes")]
    public partial class tb_clientesXPO : XPLiteObject
    {
        int fcl_id;
        [Key(true)]
        public int cl_id
        {
            get { return fcl_id; }
            set { SetPropertyValue<int>(nameof(cl_id), ref fcl_id, value); }
        }
        string fcl_nome;
        [Size(50)]
        public string cl_nome
        {
            get { return fcl_nome; }
            set { SetPropertyValue<string>(nameof(cl_nome), ref fcl_nome, value); }
        }
        string fcl_cpf;
        [Size(15)]
        public string cl_cpf
        {
            get { return fcl_cpf; }
            set { SetPropertyValue<string>(nameof(cl_cpf), ref fcl_cpf, value); }
        }
        string fcl_email;
        [Size(50)]
        public string cl_email
        {
            get { return fcl_email; }
            set { SetPropertyValue<string>(nameof(cl_email), ref fcl_email, value); }
        }
        string fcl_telefone;
        [Size(14)]
        public string cl_telefone
        {
            get { return fcl_telefone; }
            set { SetPropertyValue<string>(nameof(cl_telefone), ref fcl_telefone, value); }
        }
        DateTime fcl_data_cadastro;
        public DateTime cl_data_cadastro
        {
            get { return fcl_data_cadastro; }
            set { SetPropertyValue<DateTime>(nameof(cl_data_cadastro), ref fcl_data_cadastro, value); }
        }
    }

}
