//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LutonesSystem.XPO.LutonesSystem
{

    [Persistent(@"tb_insumos")]
    public partial class tb_insumosXPO : XPLiteObject
    {
        int fin_id;
        [Key(true)]
        public int in_id
        {
            get { return fin_id; }
            set { SetPropertyValue<int>(nameof(in_id), ref fin_id, value); }
        }
        string fin_nome;
        public string in_nome
        {
            get { return fin_nome; }
            set { SetPropertyValue<string>(nameof(in_nome), ref fin_nome, value); }
        }
        int fin_quantidade_estoque;
        public int in_quantidade_estoque
        {
            get { return fin_quantidade_estoque; }
            set { SetPropertyValue<int>(nameof(in_quantidade_estoque), ref fin_quantidade_estoque, value); }
        }
        string fin_unidade_medida;
        [Size(50)]
        public string in_unidade_medida
        {
            get { return fin_unidade_medida; }
            set { SetPropertyValue<string>(nameof(in_unidade_medida), ref fin_unidade_medida, value); }
        }
        decimal fin_preco_unitario;
        public decimal in_preco_unitario
        {
            get { return fin_preco_unitario; }
            set { SetPropertyValue<decimal>(nameof(in_preco_unitario), ref fin_preco_unitario, value); }
        }
        tb_fornecedoresXPO fin_fk_id_fornecedores;
        [Association(@"tb_insumosXPOReferencestb_fornecedoresXPO")]
        public tb_fornecedoresXPO in_fk_id_fornecedores
        {
            get { return fin_fk_id_fornecedores; }
            set { SetPropertyValue<tb_fornecedoresXPO>(nameof(in_fk_id_fornecedores), ref fin_fk_id_fornecedores, value); }
        }
    }

}
