//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LutonesSystem.XPO.LutonesSystem
{

    [Persistent(@"tb_produtos")]
    public partial class tb_produtosXPO : XPLiteObject
    {
        int fprd_id;
        [Key(true)]
        public int prd_id
        {
            get { return fprd_id; }
            set { SetPropertyValue<int>(nameof(prd_id), ref fprd_id, value); }
        }
        string fprd_nome;
        public string prd_nome
        {
            get { return fprd_nome; }
            set { SetPropertyValue<string>(nameof(prd_nome), ref fprd_nome, value); }
        }
        string fprd_descricao;
        [Size(255)]
        public string prd_descricao
        {
            get { return fprd_descricao; }
            set { SetPropertyValue<string>(nameof(prd_descricao), ref fprd_descricao, value); }
        }
        decimal fprd_preco_venda;
        public decimal prd_preco_venda
        {
            get { return fprd_preco_venda; }
            set { SetPropertyValue<decimal>(nameof(prd_preco_venda), ref fprd_preco_venda, value); }
        }
        int fprd_qtd_estoque;
        public int prd_qtd_estoque
        {
            get { return fprd_qtd_estoque; }
            set { SetPropertyValue<int>(nameof(prd_qtd_estoque), ref fprd_qtd_estoque, value); }
        }
    }

}
